name: Test
on:
  push:
    branches:
      - master
  pull_request:
  # Comment

jobs:
  test:
    runs-on: ubuntu-latest
    name: go-tree-sitter
    steps:
      - name: Check out source code
        uses: actions/checkout@v3.3.0
      - uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.19
      - name: Download dependencies
        run: go get -t ./...
      - name: Run tests
        run: go test -v ./...
